### PR TITLE
Fixed compatibility with PHP7 for Laravel 4 branch

### PR DESCRIPTION
**Pull request by billmn**
Fixed compatibility with PHP7 renaming class using reserved name

### CODE REVIEW

**Comment by barryvdh** [comment]
The default config value should be changed also, right?

**Comment by barryvdh** [comment]
Oh it did. THanks!

**Comment by dequis** [comment]
Thanks for this!

I was going to ask for a 0.6.2 release to get this change automatically, but i got this error because my `twigbridge/extensions.php` config included the old name:

>Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\String': Class TwigBridge\Extension\Laravel\String does not exist

in [ServiceProvider.php:200](https://github.com/rcrowe/TwigBridge/blob/0.6/src/ServiceProvider.php#L200)

Would it be reasonable to add an alias there by comparing strings? It's dirty but `class_alias()` won't work in php7 either.

It might also be okay to not do anything and have people manually update their composer.json and twigbridge configs if they want it to work in php7.

**Comment by cviebrock** [comment]
Not sure if this is resolved yet, but a new 0.6.x release to support PHP7 would be great.  :)

**Comment by cviebrock** [comment]
I can confirm that `composer require rcrowe/twigbridge:0.6.x-dev` and updating my _app/config/packages/rcrowe/twigbridge/extensions.php_ to enable `TwigBridge\Extension\Laravel\Str` instead of `TwigBridge\Extension\Laravel\String` is all I needed to do to get this working on Laravel 4.2 under PHP7.

**Pull request merged**
