### PR TITLE
Closes #388

### LINKED ISSUE #388: Sandbox security escalation allowing users to read configuration
I recently discovered that when using the sandbox of Twig, the global variables added by Laravel are still available. By default, [the framework adds 'app' as a shared variable in the ViewServiceProvider](https://github.com/laravel/framework/blob/master/src/Illuminate/View/ViewServiceProvider.php#L52).

The problem with this is that although by itself app, as an instance of Application is quite harmless, the [Container instance which it inherits is not](https://github.com/laravel/framework/blob/master/src/Illuminate/Container/Container.php#L1279).
Twig's sandbox requires you to add the magic `__isset()` method to your classes in order to allow the sandbox' security policy to check if the method or property you are calling on your class is allowed. Laravel's Container class does not have this method, meaning that the `__get()` method can be used freely within the sandbox, regardless of the given security policy.

The Application class contains all instances for the application, including the configuration one. This configuration can be requested by simply calling `$application->config`, which will use the magic get method to fetch the config repository, which in turn allows you to request any value from the current configuration [as it implements ArrayAccess](https://github.com/twigphp/Twig/issues/2878) (unfortunately #362 doesn't fix this as it's not a Model).

## Tl;dr
You can read the configuration of any Laravel application from within Twig's sandbox by using the global app variable added by the framework itself. 

For example:
```twig
{% sandbox %}
    {% include(template_from_string(user_template) only %}
{% endsandbox %}
```
with `user_template` being the following:
```twig
The key is {{ app.config.app.key }}
```
would produce `The key is base64:your_app_key...`, while using the `config_get()` function would result in a Twig SecurityException being thrown as intended.

I don't suppose many users of this package are even using the sandbox or care about this issue but my proposed solution for now is to remove the `app` variable from the global context by either overriding it locally for your template or from within one of your app's ServiceProviders:
```twig
{% sandbox %}
    {% include(template_from_string(user_template) with {app: null } only %}
{% endsandbox %}
```
Or in a ServiceProvider:
```php
public function boot(): void {
    View::share('app', null);
}
```

Again, I don't know how big of an issue this really is with this package itself but I thought I'd leave it here anyway so it can either be documented somewhere or discussed.

### PR DESCRIPTION
**Pull request by bytestream**

### CODE REVIEW

**Comment by bytestream** [comment]
Also closes https://github.com/rcrowe/TwigBridge/issues/378

**Comment by barryvdh** [comment]
wouldn't this be breaking, when passing normal objects?

**Comment by bytestream** [comment]
Should only be breaking if you're using a sandbox policy? But I would argue it's a bug fix and previous functionality was not intended.

**Comment by barryvdh** [comment]
But this prevents all array access fields from being accessed in a Sandbox? Or am I misunderstanding it? I understand we should prevent the app variable (eg check Container contract?), but why all ArrayAccess items?

**Comment by bytestream** [comment]
The sandbox policy should prevent access to anything that's not explicitly listed in the policy. I don't see why objects that implement `ArrayAccess` should bypass the policy with the exception of `Contract` / `Model` instances.

Looking at twig, the only side effect of this change (for those who do not use a sandbox) is that the `isset()` check on `ArrayAccess` objects is removed:
https://github.com/twigphp/Twig/blob/3.x/src/Extension/CoreExtension.php#L1370

**Comment by bytestream** [comment]
Do you mind tagging? 🤞 and if you want any help with the repo, particularly closing a lot of old issues / PR then I'm happy to help :)

**Comment by barryvdh** [comment]
Tagged 0.12
Yeah we should probably get support for 3.x in order, including getting the tests fixed (so https://github.com/rcrowe/TwigBridge/pull/395 and https://github.com/rcrowe/TwigBridge/pull/394)

**Comment by barryvdh** [comment]
This lead to problems with Symfony forms. Reverting this.

**Comment by bytestream** [comment]
> Looking at twig, the only side effect of this change (for those who do not use a sandbox) is that the isset() check on ArrayAccess objects is removed:
https://github.com/twigphp/Twig/blob/3.x/src/Extension/CoreExtension.php#L1370

> Twig's sandbox requires you to add the magic __isset() method to your classes in order to allow the sandbox' security policy to check if the method or property you are calling on your class is allowed.

I think it just needs to call isset(), but only if that method exists...

**Comment by bytestream** [comment]
@barryvdh why do we use `return $object->$item` instead of `return $object[$item]`

I don't think there would be a problem if we add `isset()` and use `$object[$item]`.

The problem seems to be we're checking for `ArrayAccess` (`offsetGet`, `offsetExists`) but as the code uses `$object->$item` it's actually using `__get`, `__isset`

I'll resubmit a PR...

**Pull request merged**
