### PR TITLE
Bump version to 0.9.2

### LINKED ISSUE #259: Incorrect version number in source
In https://github.com/rcrowe/TwigBridge/blob/master/src/Bridge.php#L29, the version is still 0.8.0.

### PR DESCRIPTION
**Pull request by tyteen4a03**
Fixes #259.

### CODE REVIEW

**Comment by barryvdh** [comment]
Actually, it's 0.10.0, or at least after it's tagged.

**Comment by tyteen4a03** [comment]
Fixed now.

**Comment by tyteen4a03** [comment]
Can you merge in 3cbe848 as well? That's the commit for 0.10.0

**Comment by barryvdh** [comment]
I did merge them both, but used the new 'squash and commit' feature, so it's just 1 commit. See https://github.com/rcrowe/TwigBridge/commit/dc045ec983e720810aa3133e9e800c8a98b2c6af

**Comment by tyteen4a03** [comment]
Ah, the commit message confused me. All good then.

**Pull request merged**
