### PR TITLE
Fix PHP 8 TypeError

### PR DESCRIPTION
**Pull request by bytestream**
Fixes:

```
TypeError : method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given
```

### CODE REVIEW

**Comment by barryvdh** [comment]
Sure

**Comment by bytestream** [comment]
Please could you create the `0.12` branch? (:

**Comment by barryvdh** [comment]
But aren't we still on 0.12? Or what is the issue?

**Comment by bytestream** [comment]
The primary issue is that `dev-master` is now using `twig/twig` `v3` and I'm not ready to upgrade - I'll just stick to my fork if you prefer. 

https://github.com/rcrowe/TwigBridge/compare/v0.12.3...master

**Comment by barryvdh** [comment]
Ah yes should probably bump to 0.13 and create a 0.12 branch from the latest version.

**Comment by bytestream** [comment]
Agreed :+1:

**Comment by bytestream** [comment]
> Ah yes should probably bump to 0.13 and create a 0.12 branch from the latest version.

Please could you do those two things? :crossed_fingers: I'll send another PR with this to the `0.12` branch and then we can tag `0.12.4`

**Comment by barryvdh** [comment]
Yes done.

**Pull request merged**
