### PR TITLE
Fix for include/templates composers not firing

### LINKED ISSUE #202: View composers for layouts and included views not firing
I'm using TwigBridge on Laravel 5 (0.7.2), I'm having an issue with view composers. More precisely view composers for layouts and included views are never fired, while composers for directly rendered views (View::make, etc) work properly.

I double checked, all my path separators are unified to `/`, so it can't be like the bug in previous versions where using dots and slashes in unison would cause composers to not fire.

Do I need to place the view composers somewhere in particular or something? Currently in my `AppProvider::boot` method

### PR DESCRIPTION
**Pull request by Anahkiasen**
### Fixed
- Fixed include/templates view composers not firing

---

Closes #202

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Test failure seems unrelated to my change

**Comment by barryvdh** [comment]
See https://github.com/laravel/framework/blob/dbb3eebf0818c584686ffb6a42a25db30cdf0440/src/Illuminate/View/Factory.php

    /**
     * Normalize a view name.
     *
     * @param  string $name
     * @return string
     */
    protected function normalizeName($name)
    {
        $delimiter = ViewFinderInterface::HINT_PATH_DELIMITER;
        if (strpos($name, $delimiter) === false) {
            return str_replace('/', '.', $name);
        }
        list($namespace, $name) = explode($delimiter, $name);
        return $namespace.$delimiter.str_replace('/', '.', $name);
    }

Should we do the same as Laravel?

**Comment by Anahkiasen** [comment]
I saw this but wasn't sure the namespace normalization wasn't already done somewhere withing TwigBridge. Will port the method over.

**Comment by barryvdh** [comment]
Yeah we're also doing something here: https://github.com/rcrowe/TwigBridge/blob/0e2693d99745eb8bbd01a80e841951c0738e1d15/src/Bridge.php#L71
So might make sure we do it only once and it the correct place.

**Comment by Anahkiasen** [comment]
Hm should I move the normalization here then?

**Comment by barryvdh** [comment]
I'm not sure. Probably.
Just need to make sure it's always called, also for the partials.

**Comment by Anahkiasen** [comment]
Like this?

**Comment by barryvdh** [comment]
Looks better. Can you squash?

**Comment by Anahkiasen** [comment]
Done

**Comment by barryvdh** [comment]
Thanks. Let me know if this fixes your problems with events etc!

**Comment by Anahkiasen** [comment]
Can i haz a 0.7.3 tag for this? :dancer:

**Comment by barryvdh** [comment]
Ehh, is this breaking or not?

If you have event listeners for the un-normalized names, they will stop working right?

So we'll need a 0.8 tag?

**Comment by Anahkiasen** [comment]
> If you have event listeners for the un-normalized names, they will stop working right?

Hm in theory no? All the names are normalized underneath so to me it's more of a bugfix

**Comment by barryvdh** [comment]
Yeah the views that are called by `view($name)`, but not the views that are inherited/child blocks, right?

**Comment by Anahkiasen** [comment]
No ok I just understood what you meant. Hm yes I guess it can be considered breaking in that way. I don't think a lot of people manually listen to `composing:` events but plugins extending on TwigBridge might so better tag it as `0.8` just to be sure indeed

**Comment by barryvdh** [comment]
Example:

test/hello.twig:
```
Hello {{ name }}

Hello {% include "test/child.twig" %}
```

test/child.twig
```
My Child!
```

Calling `view('test/hello.twig')`
Events before:
- `test.hello`
- `test/child`

Events after:
- `test.hello`
- `test.child`

So yeah, could be breaking. But it's better now :)

Gonna bump the alias just to be sure.

**Comment by barryvdh** [comment]
Tagged 0.8.0

**Comment by Anahkiasen** [comment]
Thanks!

**Pull request merged**
