### PR TITLE
Support Laravel 9

### PR DESCRIPTION
**Pull request by barryvdh**

### CODE REVIEW

**Comment by barryvdh** [comment]
Ugh, not sure if something is actually broken or if it's just the tests. If anyone wants to help, let me know.

**Comment by mbardelmeijer** [comment]
Did an attempt for fixing the tests/finder logic here: https://github.com/rcrowe/TwigBridge/pull/421

**Comment by barryvdh** [comment]
Cool thanks!

**Comment by barryvdh** [comment]
Tagged v0.13.1 with Laravel 9 support

**Pull request merged**
