### PR TITLE
Add support Laravel 5.5 🔥

### PR DESCRIPTION
**Pull request by dinhquochan**
It's compatible. Enjoy in Laravel 5.5-dev 👍

### CODE REVIEW

**Comment by barryvdh** [comment]
?

**Comment by dinhquochan** [comment]
Can you update `composer.json` to install on Laravel 5.5-dev something like that https://github.com/dinhquochan/TwigBridge/blob/master/composer.json 👍

**Comment by dinhquochan** [comment]
My repository is temporary, I just want use offical repository 💯

**Comment by barryvdh** [comment]
So why dod you close it :P

**Comment by dinhquochan** [comment]
i just delete wrong branch LOL. Closed automatic.

**Pull request closed without merging**
