### PR TITLE
Fixed compatibility with PHP7.

### PR DESCRIPTION
**Pull request by itsgoingd**
Fixed compatibility with PHP7 by renaming class using reserved name, added alias for existing PHP5 users, added PHP7 to travis configuration.

Fixes https://github.com/rcrowe/TwigBridge/issues/204.

### CODE REVIEW

**Comment by mikevrind** [comment]
@rcrowe Could you please accept this PR? I would love to see this issue solved for PHP7.

**Comment by rcrowe** [comment]
@mikevrind Travis seems to be unhappy with it - happy to merge once it's cleaned up

**Comment by mikevrind** [comment]
Travis is failing for months, but according to @barryvdh  (#200) it has someting to do with the Laravel configuration.

I already pulled changes from this request manually, nothing breaks.

**Comment by barryvdh** [comment]
Yeah ttests don't work, but also merge conflicts.

**Comment by itsgoingd** [comment]
Rebased to master and squashed into single commit.

**Comment by tylermenezes** [comment]
No more tests failing than were failing before. I worked on the failing tests a while ago but there were a bunch of things wrong.

We deployed the changes from this PR and it's confirmed working in Laravel 4.2 and 5 on both PHP 5.6 and 7-rc3

**Comment by barryvdh** [comment]
Okay thanks!

**Pull request merged**
