### PR TITLE
Don't specify an exact version

### PR DESCRIPTION
**Pull request by JN-Jones**
Allows installing TwigBridge in L5.1

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This change is wrong.

**Comment by GrahamCampbell** [comment]
Should be `5.0.*|5.1.*`.

**Comment by GrahamCampbell** [comment]
We can't assume it will work with later laravel versions than that. I see people getting this wrong so often.

**Comment by JN-Jones** [comment]
According to Semantic versioning minor versions shouldn't break anything. But well, changed it.

**Comment by GrahamCampbell** [comment]
> According to Semantic versioning minor versions shouldn't break anything. But well, changed it.

Laravel does not follow semantic versioning, and never will.

**Comment by barryvdh** [comment]
Thanks!

**Pull request merged**
